const dedicatedIndex = {
    title: "Open VZ",
    table: [
        {
            title: "XEON E3 V5",
            subtitle: "",
            cpu: "Xeon E3-1240L V5",
            cores: "2.10GHz (4 cores)",
            storage: "2x240GB SATA SSD",
            isUpgradable: true,
            data: "10TB",
            ram: "16",
            priceMonthly: 80.00,
            priceYearly: 64.00,
        },
        {
            title: "XEON E5 2620 V3",
            subtitle: "",
            cpu: "Intel Xeon Е5-2620 v3",
            cores: "2.40GHz (6 cores)",
            storage: "2x240GB SATA SSD",
            isUpgradable: true,
            data: "20TB",
            ram: "16",
            priceMonthly: 110.00,
            priceYearly: 88.00,
        },
        {
            title: "Xeon Е5 2650L v4",
            subtitle: "",
            cpu: "Intel Xeon Е5-2650L V4",
            cores: "1.70 GHz (14 cores)",
            storage: "2x240 GB SATA SSD",
            isUpgradable: true,
            data: "20TB",
            ram: "32",
            priceMonthly: 160.00,
            priceYearly: 128.00,
        },
        {
            title: "Xeon D",
            subtitle: "",
            cpu: "Xeon D-1541",
            cores: "2.1 GHz (8 cores)",
            storage: "2x240 GB SATA SSD",
            isUpgradable: true,
            data: "10TB",
            ram: "16",
            priceMonthly: 88.00,
            priceYearly: 64.00,
        },
        {
            title: "Xeon E3 v3",
            subtitle: "",
            cpu: "Xeon E3-1240L V3",
            cores: "2.00 GHz (4 cores)",
            storage: "2x480 GB SATA SSD",
            isUpgradable: true,
            data: "10TB",
            ram: "8",
            priceMonthly: 80.00,
            priceYearly: 64.00,
        },
        {
            title: "Xeon Scalable 6c",
            subtitle: "",
            cpu: "Xeon 3204/similar",
            cores: "1.9 GHz (6 cores)",
            storage: "2x240 GB NVMe",
            isUpgradable: true,
            data: "10TB",
            ram: "16",
            priceMonthly: 115.00,
            priceYearly: 92.00,
        },
        {
            title: "Xeon Scalable 8c",
            subtitle: "",
            cpu: "Xeon 4108/similar",
            cores: "2.1 GHz (8 cores)",
            storage: "2x240 GB NVMe",
            isUpgradable: true,
            data: "10TB",
            ram: "32",
            priceMonthly: 145.00,
            priceYearly: 116.00,
        },
        {
            title: "Xeon Scalable 10c",
            subtitle: "",
            cpu: "Xeon 4210/similar",
            cores: "2.2 GHz (10 cores)",
            storage: "2x480 GB NVMe",
            isUpgradable: true,
            data: "10TB",
            ram: "32",
            priceMonthly: 175.00,
            priceYearly: 140.00,
        },
        {
            title: "Xeon Scalable 16c",
            subtitle: "",
            cpu: "Xeon 6130/similar",
            cores: "2.1 GHz (10 cores)",
            storage: "2x480 GB NVMe",
            isUpgradable: true,
            data: "15TB",
            ram: "64",
            priceMonthly: 210.00,
            priceYearly: 168.00,
        },
        {
            title: "Xeon Scalable 24c",
            subtitle: "",
            cpu: "Xeon 5220R/similar",
            cores: "2.3 GHz (24 cores)",
            storage: "2x480 GB NVMe",
            isUpgradable: true,
            data: "20TB",
            ram: "64",
            priceMonthly: 270.00,
            priceYearly: 216.00,
        },
        {
            title: "Xeon Scalable 48c",
            subtitle: "",
            cpu: "2x Xeon 5220R/similar",
            cores: "2.3 GHz (48 cores)",
            storage: "2x480 GB NVMe",
            isUpgradable: true,
            data: "20TB",
            ram: "128",
            priceMonthly: 470.00,
            priceYearly: 376.00,
        },
        {
            title: "Atom 2c",
            subtitle: "",
            cpu: "Intel Atom D525",
            cores: "1.8 GHz (2 cores)",
            storage: "2x240 GB SATA SSD",
            isUpgradable: true,
            data: "10TB",
            ram: "4",
            priceMonthly: 40.00,
            priceYearly: 32.00,
        },
    ]
}

module.exports = { dedicatedIndex }